# Istio Ingress Gateway
chart: gateway
repoURL: https://istio-release.storage.googleapis.com/charts
targetRevision: 1.28.2
releaseName: istio-ingressgateway
namespace: istio-ingress
syncOptions:
  - CreateNamespace=true