global:
  domain: devops.kacperklimas.com # We need to set domain for correct proxying
configs:
  cm:
    statusbadge.enabled: true # -- Enable Status Badge
server:   # We need to apply additional config to ArgoCD helm chart to proxy traffic via Istio gateway
  podLabels: # We are injecting Istio Envoy Proxy Sidecar here using annotation for pods. Only for ArgoCD Server because is used with Ingress Gateway for now
    sidecar.istio.io/inject: "true" # If you don't want a problem with installation remember: If you need to pass some bool value as string use quotation marks "" :)
  extraArgs:
    - --staticassets
    - /shared/app
    - --redis
    - argo-cd-argocd-redis:6379
    - --insecure
    - --basehref
    - /argocd
    - --rootpath
    - /argocd
  env:
    - name: ARGOCD_MAX_CONCURRENT_LOGIN_REQUESTS_COUNT
      value: "0"