image:
  repository: acrdevopsprojecttesting.azurecr.io/storage-service
  tag: &imageTag v1.0.0-57-gb498d6b

namespace: prod

env:
  SERVER_PORT: "8080"
  RABBITMQ_HOST: rabbitmq.rabbitmq-system.svc.cluster.local

secretEnv:
  - name: BUCKET_ENDPOINT
    secretName: cloudflare-r2-credentials
    key: apiUri
  - name: BUCKET_ACCESS_KEY
    secretName: cloudflare-r2-credentials
    key: accessKeyId
  - name: BUCKET_SECRET_KEY
    secretName: cloudflare-r2-credentials
    key: secretAccessKey

healthCheck:
  enabled: false

virtualService:
  enabled: true
  host: devops.kacperklimas.com
  gateway: istio-ingress/application-gateway
  uriPrefix: /api/storage
  subsets:
    - name: v1
      weight: 100

destinationRule:
  enabled: true
  loadBalancer: LEAST_REQUEST
  subsets:
    - name: v1
      version: *imageTag