apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: networking.istio.io
      version: v1
      kind: Gateway
      name: application-gateway
      namespace: istio-ingress
    patch: |- # JSON6902 Patches
      - op: replace
        path: /spec/servers/0/hosts/0
        value: devops-testing.kacperklimas.com  
      - op: replace
        path: /spec/servers/1/hosts/0
        value: devops-testing.kacperklimas.com
  - target:
      group: networking.istio.io
      version: v1
      kind: VirtualService
      name: argocd-virtualservice
      namespace: argocd
    patch: |-
      - op: replace
        path: /spec/hosts/0
        value: devops-testing.kacperklimas.com
  - target:
      group: networking.istio.io
      version: v1
      kind: VirtualService
      name: grafana-virtualservice
      namespace: istio-system
    patch: |-
      - op: replace
        path: /spec/hosts/0
        value: devops-testing.kacperklimas.com