apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - name: storage-service-v1.0
    count: 3
images:
  - name: acrdevopsprojectprodu.azurecr.io
    newName: storage-service
    newTag: v1.0