grafana:
  ingress: # This is needed for setting correct hostname to Grafana, it creates useless Ingress resource
    enabled: true
    hosts:
      - devops-testing.kacperklimas.com
    path: /grafana