image:
  repository: acrdevopsprojecttesting.azurecr.io/demo-go
  tag: &imageTag v1.0.0-54-g387d0db

namespace: prod

healthCheck:
  enabled: false

virtualService:
  enabled: true
  host: devops-testing.kacperklimas.com
  gateway: istio-ingress/application-gateway
  uriPrefix: /api/demo-go
  subsets:
    - name: v1
      weight: 100

destinationRule:
  enabled: true
  loadBalancer: LEAST_REQUEST
  subsets:
    - name: v1
      version: *imageTag