# ESO
chart: external-secrets
syncWave: "-3"
repoURL: https://charts.external-secrets.io/
targetRevision: 1.1.0
releaseName: external-secrets
namespace: external-secrets
syncOptions:
  - CreateNamespace=true
  - ServerSideApply=true