apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: external-secrets.io
      version: v1
      kind: ClusterSecretStore
      name: azure-cluster-secret-store
    patch: |- # JSON6902 Patches
      - op: replace
        path: /spec/provider/azurekv/vaultUrl
        value: https://kv-devopsproject-stag.vault.azure.net