apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - name: user-service-v1.0
    count: 1
images:
  - name: acrdevopsproject.azurecr.io/user-service
    newName: acrdevopsprojecttest.azurecr.io/user-service
    newTag: v1.0.0-9-g99b96ae
