apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-application-set
  namespace: argocd
spec:
  goTemplate: true # We are using Go template because fasttemplate will be deprecated
  generators:

    - git:
        repoURL: https://github.com/KacperKlimas10/DevOps.git
        revision: feature/argocd-testing
        directories:
          - path: infrastructure/kubernetes/microservices/*/overlays/testing

  template:
    metadata:
      name: 'microservice-{{ index .path.segments 3 }}-testing'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io  # Cascade delete
      annotations:
        argocd.argoproj.io/sync-wave: "3"
    spec:
      project: devops-project-testing
      source:
        repoURL: https://github.com/KacperKlimas10/DevOps.git
        targetRevision: feature/argocd-testing
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            istio-injection: enabled  # To inject sidecar proxy automatically we need set this label