apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-project-testing
  namespace: argocd
spec:
  description: (Polish) Projekt inżynierski realizowany przez Kacpra Klimasa
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'