name: istio-crds # Istio CRDs
chart: base
repoURL: https://istio-release.storage.googleapis.com/charts
targetRevision: 1.28.2
releaseName: istio-base
defaultValues: "true"
namespace: istio-system
ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
      - /webhooks/0/failurePolicy
syncOptions:
  - CreateNamespace=true