apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-virtual-service.yaml
  - devops-ingress-gateway.yaml
  - mtls-lockdown-peer-authentication.yaml
  - rabbitmq-virtual-service.yaml
  - storage-service-destination-rule.yaml
  - storage-service-virtual-service.yaml
  - user-service-destination-rule.yaml
  - user-service-virtual-service.yaml