apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-virtual-service.yaml
  - ingressgateway.yaml
  - grafana-virtual-service.yaml
  - peerauthentication.yaml
  - rabbitmq-virtual-service.yaml
  - storage-service-destination-rule.yaml
  - storage-service-virtual-service.yaml
  - user-service-destination-rule.yaml
  - user-service-virtual-service.yaml