# Image 
image:
  repository: ""        # acrdevopsproject.azurecr.io/my-service
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

# Namespace 
namespace: prod

# Replicas 
replicaCount: 1

# Service 
service:
  port: 8080
  targetPort: 8080

# ServiceAccount 
serviceAccount:
  name: ""              # defaults to release name

# Resources 
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

#  Environment variables 
env: {}
  # SERVER_PORT: "8080"
  # RABBITMQ_HOST: rabbitmq.rabbitmq-system.svc.cluster.local

# Secrets injected as env vars via secretKeyRef
secretEnv: []
  # - name: POSTGRESQL_URI
  #   secretName: postgresql-credentials
  #   key: uri

#  Security context 
securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001

# Probes 
healthCheck:
  enabled: true
  livenessProbe:
    path: /actuator/health/liveness
    initialDelaySeconds: 15
    periodSeconds: 10

  readinessProbe:
    path: /actuator/health/readiness
    initialDelaySeconds: 15
    periodSeconds: 10

# Istio - VirtualService 
virtualService:
  enabled: true
  host: devops.kacperklimas.com
  gateway: istio-ingress/application-gateway
  uriPrefix: /api/change-me
  # Weights - must sum to 100
  subsets:
    - name: v1
      weight: 100
    - name: v2
      weight: 0
    - name: v3
      weight: 0

# Istio - DestinationRule 
destinationRule:
  enabled: true
  loadBalancer: LEAST_REQUEST
  subsets:
    - name: v1
      version: v1.0
    - name: v2
      version: v2.0
    - name: v3
      version: v3.0