apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-install-application-set
  namespace: argocd
spec:
  goTemplate: true # We are using Go template engines
  generators:

    - git: # Git generator automatically detects new helm chart folder and applies to cluster
        repoURL: https://github.com/KacperKlimas10/DevOps.git
        revision: feature/argocd-testing
        files:
          - path: infrastructure/kubernetes/infrastructure/helm-charts/staging/*/config.yaml

  template:
    metadata:
      name: 'helm-{{ .path.basename }}-staging' # Template points at folder containing config file; Provided by Git generator
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: '{{ default "0" .syncWave }}'
    spec:
      project: devops-project-staging
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'

  templatePatch: | # Advanced Go templating with Sprig that makes easier managing specific settings for example ignoreDifferences or Helm value files
    spec:
      sources:
        - repoURL: '{{ .repoURL }}'
          chart: '{{ .chart }}'
          targetRevision: '{{ .targetRevision }}'
          helm:
            valueFiles: # My charts have a custom values files or default
              - $values/{{ .path.path }}/values.yaml  # Reference to values files in my Git repository
            {{- range .additionalValueFiles }}
              {{ . }}
            {{- end }}
        - repoURL: https://github.com/KacperKlimas10/DevOps.git
          targetRevision: feature/argocd-testing
          ref: values
      ignoreDifferences: # This feature allows to ignore fields which makes OutOfSync status
      {{- range .ignoreDifferences }}
        - group: {{ .group }}
          kind:  {{ .kind }}
          jsonPointers:
          {{- range .jsonPointers }}
            - {{ . }}
          {{- end }}
      {{- end }}
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
        {{- range .syncOptions }}
          - {{ . }}
        {{- end }}