apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-cluster-secret-store
spec:
  provider:
    azurekv:
      environmentType: PublicCloud
      authType: WorkloadIdentity  # Terraform creates identity for this type of auth
      vaultUrl: "https://kv-devopsproject-prod.vault.azure.net" # I can't use my custom subdomain. I've written more about that issue in Terraform Private DNS Zone config
      serviceAccountRef:
        name: key-vault-integration
        namespace: external-secrets
  conditions:
    - namespaces:
        - argocd
        - prod
        - cert-manager
        - external-dns
        - external-secrets