apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-cluster-secret-store
  refreshPolicy: Periodic
  refreshInterval: 0h5m0s
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner   # Creates Kubernetes secret if ExternalSecret created
  data:
    - secretKey: api-token
      remoteRef:
        key: secret/cloudflare-api-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-cluster-secret-store
  refreshPolicy: Periodic
  refreshInterval: 0h5m0s
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: secret/cloudflare-api-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azurecr-credentials
  namespace: prod
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-cluster-secret-store
  refreshPolicy: Periodic
  refreshInterval: 0h5m0s
  target:
    name: azurecr-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "acrdevopsprojectprod.azurecr.io": {
                "username": "{{ .token }}",
                "password": "{{ .password }}"
              }
            }
          }
  data:
    - secretKey: token
      remoteRef:
        key: secret/aks-acr-token
    - secretKey: password
      remoteRef:
        key: secret/aks-acr-password