apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
    service: {{ include "microservice.fullname" . }}
spec:
  selector:
    app: {{ include "microservice.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP  