apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage-service-deployment-v1.0.yaml
  - storage-service-rbac.yaml
  - storage-service-service.yaml
  - storage-service-service-account.yaml