apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service-v1.0
  namespace: prod
  labels:
    app: storage-service
    version: v1.0
spec:
  selector:
    matchLabels:
      app: storage-service
      version: v1.0
  template:
    metadata:
      name: storage-service-v1.0
      labels:
        app: storage-service
        version: v1.0
    spec:
      containers:
        - name: storage-service
          image: acrdevopsprojectprod.azurecr.io/storage-service:v1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: RABBITMQ_HOST
              value: rabbitmq.rabbitmq-system.svc.cluster.local
            - name: BUCKET_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: cloudflare-r2-credentials
                  key: apiUri
            - name: BUCKET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-r2-credentials
                  key:  accessKeyId
            - name: BUCKET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-r2-credentials
                  key: secretAccessKey
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 1001 # Created user in Docker image
            runAsGroup: 1001
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
      imagePullSecrets: # Setting credentials to Azure Container Registry, synchronized with Key Vault
        - name: azurecr-credentials
      restartPolicy: Always
      serviceAccountName: storage-service