image:
  repository: acrdevopsprojecttesting.azurecr.io/user-service
  tag: &imageTag v1.0.0-73-gaeff590

namespace: prod

env:
  SERVER_PORT: "8080"
  RABBITMQ_HOST: rabbitmq.rabbitmq-system.svc.cluster.local

secretEnv:
  - name: POSTGRESQL_URI
    secretName: postgresql-credentials
    key: uri
  - name: POSTGRESQL_USERNAME
    secretName: postgresql-credentials
    key: username
  - name: POSTGRESQL_PASSWORD
    secretName: postgresql-credentials
    key: password

healthCheck:
  enabled: false
  
virtualService:
  enabled: true
  host: devops-testing.kacperklimas.com
  gateway: istio-ingress/application-gateway
  uriPrefix: /api/user
  subsets:
    - name: v1
      weight: 100

destinationRule:
  enabled: true
  loadBalancer: LEAST_REQUEST
  subsets:
    - name: v1
      version: *imageTag