name: 'CI: Build and Push (Building Stage)'

on:
  push:
    branches:
      - master
    paths:
      - microservices/**
    tags:
      - '*@v*.*.*' 
  workflow_dispatch:
    inputs:
      microservice:
        description: 'Microservice to build'
        required: true
        type: choice
        options: 
          - user-service
          - storage-service
          - demo-go
          - demo-python
      version:
        description: 'Image tag for choosen microservice'
        required: false
        type: string
      environment:
        description: 'Environment'
        required: true
        type: choice
        options: 
          - testing 
          - staging
          - production
        default: testing

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs: 
      microservices: ${{ steps.filter-output.outputs.microservices }}
      environment: ${{ steps.filter-output.outputs.environment }}
      version: ${{ steps.filter-output.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Changed paths filter
        if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master' }}
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # It's only used if action is triggered by a pull request event.
          filters: '.github/utils/path-filters.yaml'
      
      - name: Filter output # We need to differ how to proceed output for standard push with path filtering and pushing git tag
        id: filter-output
        shell: bash
        run: |
          set -euo pipefail

          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            msvc=$(find microservices -type d -name "${{ inputs.microservice }}" | sed 's/^\.\///') 
            echo "microservices=[\"$msvc\"]" >> "$GITHUB_OUTPUT"
            echo 'environment=${{ inputs.environment }}' >> "$GITHUB_OUTPUT"
            echo 'version=${{ inputs.version }}' >> "$GITHUB_OUTPUT"
          
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            git_tag="${{ github.ref_name }}"      
            msvc=$(find microservices -type d -name ${git_tag%%@*} | sed 's/^\.\///') 
            echo "microservices=[\"$msvc\"]" >> "$GITHUB_OUTPUT"
            echo 'environment=staging' >> "$GITHUB_OUTPUT"

          else
            echo 'microservices=${{ steps.filter.outputs.changes }}' >> "$GITHUB_OUTPUT"
            echo 'environment=testing' >> "$GITHUB_OUTPUT"
          fi
  
  build-push:
    runs-on: ubuntu-24.04      
    needs: filter
    if: ${{ needs.filter.outputs.microservices != '[]' && needs.filter.outputs.microservices != '' }}
    environment: ${{ needs.filter.outputs.environment }}
    strategy:
      matrix:
        microservice: ${{ fromJson(needs.filter.outputs.microservices) }}
      fail-fast: false
    permissions:
      id-token: write
      actions: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:  
          fetch-depth: 0 # To provide git describe working correctly we need to load full Git history

      - name: Azure Login (OIDC) # We are using OIDC Federated Workload Identity to authenticate in Azure and get permissions to push container images
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Azure ACR Login
        run: az acr login -n ${{ vars.AZURE_CONTAINER_REGISTRY }}
      
      # - name: Set up QEMU # Setting up Qemu and buildix for multiarch image bulding like AMD64 and ARM64
      #   uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
                                            
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Generate Image Tag
        id: image
        env:
          MICROSERVICE_PATH: ${{ matrix.microservice }}
          ENVIRONMENT: ${{ needs.filter.outputs.environment }}
          INPUT_VERSION: ${{ needs.filter.outputs.version }}
          AZURE_CONTAINER_REGISTRY: ${{ vars.AZURE_CONTAINER_REGISTRY }}
        shell: bash
        run: |
          set -euo pipefail
          
          microservice_name=$(basename "${MICROSERVICE_PATH}")
          prefix=$(git describe --tags --always --first-parent --match "${microservice_name}@*.*.*")

          if [[ -n "${INPUT_VERSION}" ]]; then
            tag="${INPUT_VERSION}"
          
          elif [[ "${ENVIRONMENT}" == "staging" || "${ENVIRONMENT}" == "production" ]]; then
            tag="${prefix##*@}"
            tag="${tag%%-*}"  # v1.0.0 for staging and production images
          else
            tag="${prefix##*@}" # v1.0.0-1-abc1234 for testing images
          fi
          
          echo "generated_tag=${tag}" >> "$GITHUB_OUTPUT"
          echo "generated_image=${AZURE_CONTAINER_REGISTRY}/${microservice_name}:${tag}" >> "$GITHUB_OUTPUT"

      - name: Build and Push Container Images
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          tags: ${{ steps.image.outputs.generated_image }}
          platforms: linux/amd64 #,linux/arm64 # Multiarch build
          push: true # Push after building stage 
          context: ${{ matrix.microservice }} # Path to Dockerfile
          cache-from: type=gha # To optimize building results we are using Docker Cache
          cache-to: type=gha,mode=max
      
      - name: Run Update GitOps Manifest Workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail

          gh workflow run update-gitops-manifest.yaml \
            -f microservice=$(basename "${{ matrix.microservice }}") \
            -f image_tag="${{ steps.image.outputs.generated_tag }}" \
            -f environment="${{ needs.filter.outputs.environment }}"