name: Run Linter (Validattion Stage)

on:
  push:
    branches:
      - master
    paths:
      - microservices/**
      - .github/workflows/lint.yaml
  pull_request:
  workflow_dispatch:

jobs:
  run-linter:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false  