name: Run Tests (Validation Stage)

on:
  push:
    branches:
      - master
    paths:
      - microservices/**
      - .github/workflows/test.yaml
  pull_request:
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-22.04
    outputs: 
      microservies: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Changed paths filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # It's only used if action is triggered by a pull request event.
          filters: '.github/utils/path-filters.yaml'

  run-tests:
    runs-on: ubuntu-22.04
    needs: filter
    if: ${{ needs.filter.outputs.microservies != '[]' && needs.filter.outputs.microservies != '' }}
    strategy:
      matrix:
        microservice: ${{ fromJson(needs.filter.outputs.microservies) }}
      fail-fast: false 
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup JDK
        if: ${{ startsWith(matrix.microservice, 'microservices/java') }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        if: ${{ startsWith(matrix.microservice, 'microservices/java') }}
        run: mvn test
