global:
  domain: argocd-staging.kacperklimas.com # We need to set domain for correct proxying
configs:
  params:
    server.insecure: "true"
  cm:
    statusbadge.enabled: true # -- Enable Status Badge